### PR TITLE
Fix typo in doc for `rush add`

### PR DESCRIPTION
**Pull request by hugmoro**
Hi,
I believe `rush add --project "example@^1.2.3"` is some kind of typo.
Here's a PR to change this to `rush add --package "example@^1.2.3"`.

### CODE REVIEW

**Comment by octogonz** [comment]
Thanks @hugmoro!  We should fix the command line that this is based on. See here:
https://github.com/Microsoft/web-build-tools/blob/master/apps/rush-lib/src/cli/actions/AddAction.ts

**Comment by hugmoro** [comment]
Oh, I see, I just clicked the button in the doc page to suggest this fix :)

So, should I create an issue in `rush-lib` then?
And maybe a PR, but I have not looked at the source yet seriously enough to get an idea of what fixing this would entail -- and maybe it would affect other parts that you guys would prefer to deal with yourselves?

**Comment by octogonz** [comment]
@hugmoro most of the documentation pages are manually authored.  However the command-line help corresponds to the actual tool output when you run `rush add --help`.

So the right way to fix this is by modifying the tool itself.

**Comment by octogonz** [comment]
Here's a PR for Rush itself: https://github.com/microsoft/web-build-tools/pull/1297

**Pull request merged**
